package main

// NAMES is the 68-name leaderboard list, mirrored verbatim from
// games/typescript/src/leaderboard/names.ts. Order and spelling
// are preserved exactly — including the "Georgep Gervin" typo —
// because the curated power order is part of the design.
//
// Inner quotes use single quotes so the names match the
// TypeScript strings without escaping.
var NAMES = []string{
	"Zeus",
	"Michael Jordan",
	"Walter White",
	"Charlie Bucket",
	"Denzel Washington",
	"Shaquille O'Neal",
	"Allen 'The Answer' Iverson",
	"Bruce Wayne",
	"Blade",
	"Apollo Creed",
	"Kobe Bryant",
	"L Lawliet",
	"Bruce Lee",
	"Gene Wilder",
	"Samuel L. Jackson",
	"Hakeem Olajuwon",
	"Earvin 'Magic' Johnson",
	"Peter Parker",
	"Morpheus",
	"Muhammad Ali",
	"Kevin Durant",
	"Lelouch Lamperouge",
	"James Bond",
	"Giancarlo Esposito",
	"Wilt Chamberlain",
	"Julius 'Dr. J' Erving",
	"T'Challa",
	"John Wick",
	"Nicolas Cage",
	"Lucifer Morningstar",
	"God",
	"LeBron James",
	"Light Yagami",
	"Willy Wonka",
	"Don Cheadle",
	"Kareem A. Jabbar",
	"Pete 'Pistol' Maravich",
	"Tony Stark",
	"Wesley Snipes",
	"Odin",
	"Kawhi Leonard",
	"Gus Fring",
	"Maximus Decimus Meridius",
	"Idris Elba",
	"Moses Malone",
	"Clyde 'The Glide' Drexler",
	"Clark Kent",
	"Alucard",
	"Clubber Lang",
	"Tracy McGrady",
	"Johan Liebert",
	"Ip Man",
	"Christopher Walken",
	"Mahershala Ali",
	"David Robinson",
	"Dominique 'The Human Highlight Film' Wilkins",
	"Erik Killmonger",
	"Vincent Vega",
	"Laurence Fishburne",
	"Hades",
	"Damian Lillard",
	"Spike Spiegel",
	"Thomas Shelby",
	"Keith David",
	"Georgep Gervin",
	"Paul 'The Truth' Pierce",
	"Miles Morales",
	"Frank Castle",
}
